In [13]:
import os
import sys
import pymssql
import locale

sys.path.append(os.path.abspath(".."))

import pandas as pd
import numpy as np


from dotenv import load_dotenv
from num2words import num2words
from docxtpl import DocxTemplate
from docx2pdf import convert
from utils_ccd import get_connection, generate_pdf_office

load_dotenv()
conn = get_connection()
locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')

'pt_BR.UTF-8'

In [15]:
# mês atual, ano atual
from datetime import datetime
now = datetime.now()
mes_atual = now.month
ano_atual = now.year


#somar valores das multas

In [14]:
descontos_sql = f''' 
SELECT 
    pro.numero_processo,
    pro.ano_processo,
    pro.assunto,
    pm.Descricao as descricao,
    CONCAT(gp.Nome, ' (CPF: ', gp.Documento, ')') as nome,
    processo.dbo.fn_Exe_RetornaValorAtualizado(ed.IdDebito) as valor_multa,
    orgao_info.nome_orgao,
    ed.CodigoStatusDivida as status_divida
FROM processo.dbo.Processos pro
INNER JOIN processo.dbo.Pro_MarcadorProcesso pmp 
    ON pmp.IdProcesso = pro.IdProcesso
INNER JOIN processo.dbo.Pro_Marcador pm 
    ON pmp.IdMarcador = pm.IdMarcador
LEFT JOIN processo.dbo.Exe_Debito ed 
    ON ed.IdProcessoExecucao = pro.IdProcesso
LEFT JOIN processo.dbo.Exe_DebitoPessoa edp 
    ON edp.IDDebito = ed.IdDebito
LEFT JOIN processo.dbo.GenPessoa gp 
    ON gp.IdPessoa = edp.IDPessoa
OUTER APPLY (
    SELECT TOP 1 vspfr.nome_orgao
    FROM BdDIP.dbo.vwSiaiPessoalFolhaResumida vspfr
    WHERE vspfr.cpf = gp.Documento COLLATE SQL_Latin1_General_CP1_CI_AS
    AND vspfr.mes = 12 AND vspfr.ano = 2025
    ORDER BY vspfr.ano DESC, vspfr.mes DESC
) AS orgao_info
WHERE 
    pro.setor_atual = 'CCD'
    AND pm.Descricao LIKE 'DESCONTO EM FOLHA - Implementar'
    AND ed.CodigoTipoDebito IN (2, 5)
'''
processos_descontos = pd.read_sql(descontos_sql, conn)

In [16]:
processos_descontos

,numero_processo,ano_processo,assunto,descricao,nome,valor_multa,nome_orgao,status_divida
0,003669,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,EMANUEL DA SILVA GALDINO (CPF: 63453908449),1149.1111,None,1
1,003670,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,Evilasia Gildenia de Oliveira (CPF: 03029737454),5561.1012,None,1
2,003672,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,MARIA DAS GRAÇAS MARQUES SILVA (CPF: 12354210400),5515.2300,CÂMARA MUNICIPAL DE MONTE ALEGRE,1
3,003674,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,JOSENEIDE CUNHA DE MEDEIROS (CPF: 67340768491),38119.9210,None,1
4,002725,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,CLEMENCEAU ALVES (CPF: 26162180468),8243.4036,SECRETARIA DE ESTADO DA ADMINISTRAÇÃO,1
5,002725,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,CLEMENCEAU ALVES (CPF: 26162180468),25805.4349,SECRETARIA DE ESTADO DA ADMINISTRAÇÃO,1
6,002725,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,CLEMENCEAU ALVES (CPF: 26162180468),119.4697,SECRETARIA DE ESTADO DA ADMINISTRAÇÃO,1
7,003664,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,ALYSSON MOISÉS DE MEDEIROS (CPF: 03163340490),11185.6832,None,1
8,003671,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,CELSO LUIZ MARINHO LISBOA (CPF: 02587596408),1154.1271,None,1
9,003674,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,JOSENEIDE CUNHA DE MEDEIROS (CPF: 67340768491),1126.6555,None,1
10,002725,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,RONALDO DE OLIVEIRA TEIXEIRA (CPF: 42362385787),6646.7100,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,3
11,001380,2021,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,Ivete Matias Xavier (CPF: 20153104449),476.0945,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,1
12,003669,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,EMANUEL DA SILVA GALDINO (CPF: 63453908449),20684.0019,None,1
13,003674,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,JOSENEIDE CUNHA DE MEDEIROS (CPF: 67340768491),1126.6555,None,1
14,003663,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,FRANCISCO DANTAS DE ARAUJO (CPF: 36912247415),12007.8711,None,1
15,002725,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,RONALDO DE OLIVEIRA TEIXEIRA (CPF: 42362385787),4431.1485,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,1
16,002732,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,MANOEL DOS SANTOS BERNARDO (CPF: 02897647426),NaN,"SECRETARIA DE ESTADO DA EDUCAÇÃO, DA CULTURA, ...",1
17,001380,2021,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,Ivete Matias Xavier (CPF: 20153104449),1190.0936,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,13
18,002725,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,RONALDO DE OLIVEIRA TEIXEIRA (CPF: 42362385787),9228.1237,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,3
19,002732,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,MANOEL DOS SANTOS BERNARDO (CPF: 02897647426),22650.1955,"SECRETARIA DE ESTADO DA EDUCAÇÃO, DA CULTURA, ...",15
20,002731,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,JOSÉ ARACLEIDE DE ARAÚJO (CPF: 66416841487),6743.3981,PREFEITURA MUNICIPAL DE SÃO BENTO DO TRAIRÍ,1
21,003665,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,Fabio Bezerra de Oliveira (CPF: 03470464448),5252.8546,PREFEITURA MUNICIPAL DE SERRA DO MEL,1
22,002730,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,MANOEL DOS SANTOS BERNARDO (CPF: 02897647426),5311.1973,"SECRETARIA DE ESTADO DA EDUCAÇÃO, DA CULTURA, ...",1
23,003003,2021,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,CARLOS VERIANO DE LIMA (CPF: 03245923457),7315.0603,PREFEITURA MUNICIPAL DE PARAZINHO,1
24,003047,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,Marconi Antonio Praxedes Barreto (CPF: 0692689...,5252.8546,None,1
25,002729,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,FRANCISCO BRUNO FERREIRA DA COSTA (CPF: 077605...,36379.5356,ASSEMBLEIA LEGISLATIVA DO ESTADO DO RN,1
26,003045,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,ROSALBA CIARLINI ROSADO (CPF: 19951698468),6480.5096,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,1
27,003045,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,LAWRENCE CARLOS AMORIM DE ARAÚJO (CPF: 0466105...,6480.5096,None,16
28,003003,2021,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,CARLOS VERIANO DE LIMA (CPF: 03245923457),7918.8137,PREFEITURA MUNICIPAL DE PARAZINHO,1
29,003666,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,JUACEMA CONSTRUÇÕES LTDA (CPF: 03596019000130),846.1272,None,1
30,003666,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,ABEL BELARMINO DE AMORIM FILHO (CPF: 30732921449),1692.2546,None,1
31,003663,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,FRANCISCO DANTAS DE ARAUJO (CPF: 36912247415),51874.0026,None,1
32,001380,2021,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,Ivete Matias Xavier (CPF: 20153104449),5587.7249,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,3
33,001380,2021,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,Ivete Matias Xavier (CPF: 20153104449),6611.1872,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,13
34,001380,2021,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,Ivete Matias Xavier (CPF: 20153104449),6941.7370,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,13
35,001380,2021,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,Ivete Matias Xavier (CPF: 20153104449),7272.2869,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,13
36,001380,2021,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,Ivete Matias Xavier (CPF: 20153104449),7602.8367,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,13
37,001380,2021,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,Ivete Matias Xavier (CPF: 20153104449),8263.9363,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,13
38,001380,2021,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,Ivete Matias Xavier (CPF: 20153104449),10908.3350,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,13
39,001380,2021,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,Ivete Matias Xavier (CPF: 20153104449),11569.4347,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,13
40,001380,2021,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,Ivete Matias Xavier (CPF: 20153104449),9340.0588,INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,3

In [17]:
processos_descontos = processos_descontos[~processos_descontos.nome_orgao.isna()]

In [18]:
def criar_valor_extenso(x):
        if x and x > 1:
            f = lambda c: num2words(int(c), lang='pt_BR')
            return ' reais e '.join([f(y) for y in str('{:.2f}'.format(x)).split('.')]) + ' centavos'
        else:
            return ''

def converter_valor(x):
    if x:
        return locale.currency(x, grouping=True) + ' (' + criar_valor_extenso(x) + ')'
    else:
        return 'R$ 0,00 (zero)'

In [19]:
processos_descontos.fillna(0, inplace=True)

C:\Users\05911205424\AppData\Local\Temp\ipykernel_22552\3848932403.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processos_descontos.fillna(0, inplace=True)

In [20]:
processos_descontos = processos_descontos.groupby(['numero_processo', 'ano_processo', 'assunto', 'descricao', 'nome'
    ,'nome_orgao', 'status_divida']).valor_multa.sum().reset_index()

In [21]:
processos_descontos['processo'] = processos_descontos['numero_processo'] + '/' + processos_descontos['ano_processo'].astype(str)
processos_descontos['valor'] = processos_descontos['valor_multa'].apply(converter_valor)

In [22]:
processos_descontos

,numero_processo,ano_processo,assunto,descricao,nome,nome_orgao,status_divida,valor_multa,processo,valor
0,001380,2021,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,Ivete Matias Xavier (CPF: 20153104449),INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,1,476.0945,001380/2021,"R$ 476,09 (quatrocentos e setenta e seis reais..."
1,001380,2021,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,Ivete Matias Xavier (CPF: 20153104449),INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,3,14927.7837,001380/2021,"R$ 14.927,78 (catorze mil, novecentos e vinte ..."
2,001380,2021,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,Ivete Matias Xavier (CPF: 20153104449),INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,13,60359.8474,001380/2021,"R$ 60.359,85 (sessenta mil, trezentos e cinque..."
3,002725,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,CLEMENCEAU ALVES (CPF: 26162180468),SECRETARIA DE ESTADO DA ADMINISTRAÇÃO,1,34168.3082,002725/2025,"R$ 34.168,31 (trinta e quatro mil, cento e ses..."
4,002725,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,RONALDO DE OLIVEIRA TEIXEIRA (CPF: 42362385787),INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,1,4431.1485,002725/2025,"R$ 4.431,15 (quatro mil, quatrocentos e trinta..."
5,002725,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,RONALDO DE OLIVEIRA TEIXEIRA (CPF: 42362385787),INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,3,15874.8337,002725/2025,"R$ 15.874,83 (quinze mil, oitocentos e setenta..."
6,002729,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,FRANCISCO BRUNO FERREIRA DA COSTA (CPF: 077605...,ASSEMBLEIA LEGISLATIVA DO ESTADO DO RN,1,36379.5356,002729/2025,"R$ 36.379,54 (trinta e seis mil, trezentos e s..."
7,002730,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,MANOEL DOS SANTOS BERNARDO (CPF: 02897647426),"SECRETARIA DE ESTADO DA EDUCAÇÃO, DA CULTURA, ...",1,5311.1973,002730/2025,"R$ 5.311,20 (cinco mil, trezentos e onze reais..."
8,002731,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,JOSÉ ARACLEIDE DE ARAÚJO (CPF: 66416841487),PREFEITURA MUNICIPAL DE SÃO BENTO DO TRAIRÍ,1,6743.3981,002731/2025,"R$ 6.743,40 (seis mil, setecentos e quarenta e..."
9,002732,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,MANOEL DOS SANTOS BERNARDO (CPF: 02897647426),"SECRETARIA DE ESTADO DA EDUCAÇÃO, DA CULTURA, ...",1,0.0000,002732/2025,"R$ 0,00 (zero)"
10,002732,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,MANOEL DOS SANTOS BERNARDO (CPF: 02897647426),"SECRETARIA DE ESTADO DA EDUCAÇÃO, DA CULTURA, ...",15,22650.1955,002732/2025,"R$ 22.650,20 (vinte e dois mil, seiscentos e c..."
11,003003,2021,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,CARLOS VERIANO DE LIMA (CPF: 03245923457),PREFEITURA MUNICIPAL DE PARAZINHO,1,15233.8740,003003/2021,"R$ 15.233,87 (quinze mil, duzentos e trinta e ..."
12,003045,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,ROSALBA CIARLINI ROSADO (CPF: 19951698468),INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,1,6480.5096,003045/2025,"R$ 6.480,51 (seis mil, quatrocentos e oitenta ..."
13,003665,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,Fabio Bezerra de Oliveira (CPF: 03470464448),PREFEITURA MUNICIPAL DE SERRA DO MEL,1,5252.8546,003665/2025,"R$ 5.252,85 (cinco mil, duzentos e cinquenta e..."
14,003672,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,MARIA DAS GRAÇAS MARQUES SILVA (CPF: 12354210400),CÂMARA MUNICIPAL DE MONTE ALEGRE,1,5515.2300,003672/2025,"R$ 5.515,23 (cinco mil, quinhentos e quinze re..."

In [23]:
descontos_aberto = processos_descontos[processos_descontos.status_divida == 1]

In [24]:
descontos_aberto

,numero_processo,ano_processo,assunto,descricao,nome,nome_orgao,status_divida,valor_multa,processo,valor
0,001380,2021,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,Ivete Matias Xavier (CPF: 20153104449),INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,1,476.0945,001380/2021,"R$ 476,09 (quatrocentos e setenta e seis reais..."
3,002725,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,CLEMENCEAU ALVES (CPF: 26162180468),SECRETARIA DE ESTADO DA ADMINISTRAÇÃO,1,34168.3082,002725/2025,"R$ 34.168,31 (trinta e quatro mil, cento e ses..."
4,002725,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,RONALDO DE OLIVEIRA TEIXEIRA (CPF: 42362385787),INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,1,4431.1485,002725/2025,"R$ 4.431,15 (quatro mil, quatrocentos e trinta..."
6,002729,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,FRANCISCO BRUNO FERREIRA DA COSTA (CPF: 077605...,ASSEMBLEIA LEGISLATIVA DO ESTADO DO RN,1,36379.5356,002729/2025,"R$ 36.379,54 (trinta e seis mil, trezentos e s..."
7,002730,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,MANOEL DOS SANTOS BERNARDO (CPF: 02897647426),"SECRETARIA DE ESTADO DA EDUCAÇÃO, DA CULTURA, ...",1,5311.1973,002730/2025,"R$ 5.311,20 (cinco mil, trezentos e onze reais..."
8,002731,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,JOSÉ ARACLEIDE DE ARAÚJO (CPF: 66416841487),PREFEITURA MUNICIPAL DE SÃO BENTO DO TRAIRÍ,1,6743.3981,002731/2025,"R$ 6.743,40 (seis mil, setecentos e quarenta e..."
9,002732,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,MANOEL DOS SANTOS BERNARDO (CPF: 02897647426),"SECRETARIA DE ESTADO DA EDUCAÇÃO, DA CULTURA, ...",1,0.0000,002732/2025,"R$ 0,00 (zero)"
11,003003,2021,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,CARLOS VERIANO DE LIMA (CPF: 03245923457),PREFEITURA MUNICIPAL DE PARAZINHO,1,15233.8740,003003/2021,"R$ 15.233,87 (quinze mil, duzentos e trinta e ..."
12,003045,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,ROSALBA CIARLINI ROSADO (CPF: 19951698468),INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO RN,1,6480.5096,003045/2025,"R$ 6.480,51 (seis mil, quatrocentos e oitenta ..."
13,003665,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,Fabio Bezerra de Oliveira (CPF: 03470464448),PREFEITURA MUNICIPAL DE SERRA DO MEL,1,5252.8546,003665/2025,"R$ 5.252,85 (cinco mil, duzentos e cinquenta e..."
14,003672,2025,EXECUÇÃO DA DECISÃO PROFERIDA NOS AUTOS DO PRO...,DESCONTO EM FOLHA - Implementar,MARIA DAS GRAÇAS MARQUES SILVA (CPF: 12354210400),CÂMARA MUNICIPAL DE MONTE ALEGRE,1,5515.2300,003672/2025,"R$ 5.515,23 (cinco mil, quinhentos e quinze re..."

In [25]:
for desconto in descontos_aberto.itertuples():
    doc = DocxTemplate("templates/desconto_folha.docx")
    context = {
        'processo': desconto.processo,
        'assunto': desconto.assunto,
        'nome': desconto.nome,
        'orgao': desconto.nome_orgao,
        'valor': desconto.valor
    }
    nome = desconto.nome.split()[0].lower()
    processo_underline = desconto.processo.replace('/', '_')

    doc.render(context)
    d = f"saidas/desconto_folha/{processo_underline}_{nome}.docx"
    doc.save(d)
    generate_pdf_office(d, "saidas/desconto_folha/")
    print(f"Gerado arquivo para o processo {desconto.processo}")

Gerado arquivo para o processo 001380/2021
Gerado arquivo para o processo 002725/2025
Gerado arquivo para o processo 002725/2025
Gerado arquivo para o processo 002729/2025
Gerado arquivo para o processo 002730/2025
Gerado arquivo para o processo 002731/2025
Gerado arquivo para o processo 002732/2025
Gerado arquivo para o processo 003003/2021
Gerado arquivo para o processo 003045/2025
Gerado arquivo para o processo 003665/2025
Gerado arquivo para o processo 003672/2025